### ISSUE TITLE
Translated document has strange behavior when using non standard language string

### ISSUE THREAD

**Issue by HashimotoYT** [electron/i18n#836]
Document: https://github.com/electron/i18n/blob/master/content/en-US/docs/api/screen.md

English:

![english](https://user-images.githubusercontent.com/24681191/65374109-c0d28680-dc8e-11e9-984e-aefc3295ab74.png)

Ukrainian:

![ukrainian](https://user-images.githubusercontent.com/24681191/65374121-f0818e80-dc8e-11e9-8da0-959ad92506a4.png)

/cc @crowdin-support @Andrulko

**Comment by crowdin-support** [comment]
I'm already creating the task for the developers to take a look into this! I will keep you updated on any comments

**Comment by HashimotoYT** [comment]
friendly ping @crowdin-support, its have any progress?

**Comment by crowdin-support** [comment]
Hi @HashimotoYT Sorry for the delays with the update, the issue is already fixed in the new version of MD parter. 

It's just necessary to update the source file in the project in order to apply the latest improvements

**Comment by HashimotoYT** [comment]
@crowdin-support This still relevant for us. Can you please describe steps what's we should do to fix this problem?

> It's just necessary to update the source file in the project in order to apply the latest improvements

Here's needed to update the source file (`screen.md`)? If yes, we did a big update for docs when the version updated from 6.0 to 7.0, but the problem still occurs.

**Comment by Olena1234** [comment]
Hi @HashimotoYT ! Yes, you are right. Source file should be updated in the project. Could you please do this once again and let me know the result?

**Comment by HashimotoYT** [comment]
@Olena1234 This change https://github.com/electron/electron/pull/21291/files be good for this?

**Comment by Olena1234** [comment]
@HashimotoYT Yes, you have updated the file. Could you please let me know if the issue persist?
Meanwhile, checking all the details with the developers from my side

**Comment by HashimotoYT** [comment]
@Olena1234 This is the first part of updating this file (PR Stage). When the file be dropped in this repo and update in Crowdin I can give an update about this issue. This can take 1-2 weeks.

**Comment by rohalskyy** [comment]
@HashimotoYT Sure, take your time!

**Comment by Olena1234** [comment]
@HashimotoYT Just came back with the news from developers. In case update of the file won't work, could you please try to re-import the file? You can delete this file in Crowdin in the Files tab -> three dots next to the file -> Delete and then press Sync now in the Integrations tab to synchronize this file with Crowdin once again. After the re-import, all translations can be restored with the Pre-translation via TM option

**Comment by HashimotoYT** [comment]
@Olena1234 I deleted this file from the Files and click Sync at the Integration tab but file did not synchronized.

**Comment by YuliyaHarashchuk** [comment]
@HashimotoYT checking all the details on our side,

**Comment by YuliyaHarashchuk** [comment]
@HashimotoYT I'm back with the update about the synchronization: would you please try to click _Pause/Resume_ button in the _Integration_ tab?

With _Pause/Resume_ the source file and the translated files will be sent to Crowdin project again

**Comment by HashimotoYT** [comment]
Pause/Resume fixes synchronization issue. The problem fixed after remove and pulling this file. Thanks all for help ❤️.
